import { QuizCategory, QuizPack, Question, Achievement, UserProfile } from '../types';

export const DEFAULT_MASTER_ADMIN: UserProfile = {
  id: 'master-admin-001',
  username: 'MasterAdmin',
  email: 'admin@100picsquiz.com',
  role: 'admin',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=250&q=80',
  coins: 2500,
  xp: 12500,
  level: 25,
  title: 'Quiz Master Administrator',
  currentStreak: 14,
  longestStreak: 30,
  lastLoginDate: new Date().toISOString().split('T')[0],
  createdAt: '2025-01-01',
};

export const DEFAULT_PLAYER: UserProfile = {
  id: 'player-guest-101',
  username: 'TriviaExplorer',
  email: 'player@100picsquiz.com',
  role: 'player',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=250&q=80',
  coins: 150,
  xp: 420,
  level: 4,
  title: 'Puzzle Detective',
  currentStreak: 3,
  longestStreak: 5,
  lastLoginDate: new Date().toISOString().split('T')[0],
  createdAt: '2026-06-15',
};

export const INITIAL_CATEGORIES: QuizCategory[] = [
  {
    id: 'cat-logos',
    name: 'Logos & Brands',
    slug: 'logos',
    description: 'World-famous company symbols and brand marks.',
    icon: 'Sparkles',
    color: '#3B82F6', // Blue
  },
  {
    id: 'cat-flags',
    name: 'World Flags',
    slug: 'flags',
    description: 'National flags from countries across the globe.',
    icon: 'Flag',
    color: '#10B981', // Green
  },
  {
    id: 'cat-movies',
    name: 'Movies & TV',
    slug: 'movies',
    description: 'Iconic movie characters, villains, and TV heroes.',
    icon: 'Film',
    color: '#EC4899', // Pink
  },
  {
    id: 'cat-animals',
    name: 'Wild Animals',
    slug: 'animals',
    description: 'Exotic creatures, birds, and sea life.',
    icon: 'Dog',
    color: '#F59E0B', // Amber
  },
  {
    id: 'cat-landmarks',
    name: 'Landmarks',
    slug: 'landmarks',
    description: 'Wonders of the world and architectural icons.',
    icon: 'Landmark',
    color: '#8B5CF6', // Purple
  },
  {
    id: 'cat-games',
    name: 'Retro Video Games',
    slug: 'games',
    description: 'Classic arcade and video game legends.',
    icon: 'Gamepad2',
    color: '#EF4444', // Red
  },
  {
    id: 'cat-food',
    name: 'Food & Delights',
    slug: 'food',
    description: 'Delicious dishes, snacks, and global cuisines.',
    icon: 'Utensils',
    color: '#14B8A6', // Teal
  },
  {
    id: 'cat-music',
    name: 'Pop Stars & Music',
    slug: 'music',
    description: 'Legendary musicians and chart-topping icons.',
    icon: 'Music',
    color: '#6366F1', // Indigo
  }
];

export const INITIAL_PACKS: QuizPack[] = [
  {
    id: 'pack-famous-logos',
    title: 'Famous Brands & Logos',
    description: 'Test your knowledge on the world’s most recognizable brand logos!',
    category: 'Logos & Brands',
    difficulty: 'Easy',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-blue-600 to-indigo-700',
    releaseDate: '2026-01-10',
    estimatedTime: '5 mins',
    totalQuestions: 10,
    xpReward: 250,
    coinReward: 100,
    downloadSize: '2.4 MB',
    isFeatured: true,
    isPopular: true,
    tags: ['logos', 'brands', 'tech', 'pop-culture'],
  },
  {
    id: 'pack-world-flags',
    title: 'World Flags Challenge',
    description: 'Can you identify these national flags from every continent?',
    category: 'World Flags',
    difficulty: 'Medium',
    thumbnail: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-emerald-600 to-teal-700',
    releaseDate: '2026-02-01',
    estimatedTime: '6 mins',
    totalQuestions: 10,
    xpReward: 300,
    coinReward: 120,
    downloadSize: '1.8 MB',
    isFeatured: true,
    isNew: true,
    tags: ['flags', 'geography', 'countries'],
  },
  {
    id: 'pack-movie-icons',
    title: 'Movie Heroes & Legends',
    description: 'Guess the legendary film characters from cinema history!',
    category: 'Movies & TV',
    difficulty: 'Medium',
    thumbnail: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-fuchsia-600 to-pink-700',
    releaseDate: '2026-03-15',
    estimatedTime: '7 mins',
    totalQuestions: 10,
    xpReward: 350,
    coinReward: 150,
    downloadSize: '3.1 MB',
    isPopular: true,
    tags: ['movies', 'cinema', 'characters'],
  },
  {
    id: 'pack-wild-animals',
    title: 'Animals of the Wild',
    description: 'Discover fascinating mammals, birds, and exotic reptiles!',
    category: 'Wild Animals',
    difficulty: 'Easy',
    thumbnail: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef9?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef9?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-amber-500 to-orange-600',
    releaseDate: '2026-04-05',
    estimatedTime: '5 mins',
    totalQuestions: 10,
    xpReward: 200,
    coinReward: 90,
    downloadSize: '2.9 MB',
    isNew: true,
    tags: ['animals', 'nature', 'wildlife'],
  },
  {
    id: 'pack-world-landmarks',
    title: 'Wonders & Landmarks',
    description: 'Identify famous monuments, towers, and ancient wonders.',
    category: 'Landmarks',
    difficulty: 'Hard',
    thumbnail: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-purple-600 to-indigo-800',
    releaseDate: '2026-05-01',
    estimatedTime: '8 mins',
    totalQuestions: 10,
    xpReward: 400,
    coinReward: 180,
    downloadSize: '3.5 MB',
    isFeatured: true,
    tags: ['landmarks', 'travel', 'architecture'],
  },
  {
    id: 'pack-retro-games',
    title: 'Retro Video Game Classics',
    description: 'Arcade legends, pixel heroes, and gaming icons!',
    category: 'Retro Video Games',
    difficulty: 'Hard',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-red-600 to-rose-800',
    releaseDate: '2026-05-20',
    estimatedTime: '6 mins',
    totalQuestions: 8,
    xpReward: 320,
    coinReward: 140,
    downloadSize: '2.0 MB',
    tags: ['gaming', 'arcade', 'retro'],
  },
  {
    id: 'pack-food-delights',
    title: 'Tasty Food & Snacks',
    description: 'Mouth-watering dishes and sweet treats from around the globe.',
    category: 'Food & Delights',
    difficulty: 'Easy',
    thumbnail: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-teal-600 to-cyan-700',
    releaseDate: '2026-06-01',
    estimatedTime: '5 mins',
    totalQuestions: 8,
    xpReward: 220,
    coinReward: 95,
    downloadSize: '2.2 MB',
    tags: ['food', 'cuisine', 'snacks'],
  },
  {
    id: 'pack-music-icons',
    title: 'Pop Stars & Rock Legends',
    description: 'Unforgettable singers and chart-topping music icons.',
    category: 'Pop Stars & Music',
    difficulty: 'Expert',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80',
    banner: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=1200&q=80',
    packColor: 'from-violet-600 to-purple-900',
    releaseDate: '2026-06-10',
    estimatedTime: '8 mins',
    totalQuestions: 8,
    xpReward: 450,
    coinReward: 200,
    downloadSize: '2.8 MB',
    tags: ['music', 'pop', 'rock', 'celebrities'],
  }
];

export const INITIAL_QUESTIONS: Question[] = [
  // --- PACK: Famous Brands & Logos (10 Questions) ---
  {
    id: 'q-logo-1',
    packId: 'pack-famous-logos',
    order: 1,
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'NIKE',
    alternativeAcceptedAnswers: ['NIKE SHOES', 'SWOOSH'],
    difficulty: 'Easy',
    hint: 'Famous athletic footwear brand with the Swoosh logo.',
    triviaFact: 'The Nike "Swoosh" logo was created in 1971 by graphic design student Carolyn Davidson for just $35!',
    category: 'Logos & Brands',
    tags: ['logo', 'sports', 'footwear'],
    copyrightInfo: 'Fair use educational depiction',
    imageCredit: 'Unsplash / Nike Product'
  },
  {
    id: 'q-logo-2',
    packId: 'pack-famous-logos',
    order: 2,
    image: 'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'APPLE',
    alternativeAcceptedAnswers: ['APPLE INC', 'MACINTOSH'],
    difficulty: 'Easy',
    hint: 'Tech giant known for iPhone, iPad, and Mac computers.',
    triviaFact: 'The original Apple logo featured Sir Isaac Newton sitting under an apple tree before switching to the bitten apple logo in 1977.',
    category: 'Logos & Brands',
    tags: ['tech', 'brands'],
    imageCredit: 'Unsplash / Apple Inc.'
  },
  {
    id: 'q-logo-3',
    packId: 'pack-famous-logos',
    order: 3,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'MCDONALDS',
    alternativeAcceptedAnswers: ['MCDONALD', 'MCDONALDS'],
    difficulty: 'Easy',
    hint: 'Fast food chain famous for Golden Arches and the Big Mac.',
    triviaFact: 'McDonald’s Golden Arches are recognized by more people globally than the Christian cross!',
    category: 'Logos & Brands',
    tags: ['food', 'fastfood', 'brand'],
    imageCredit: 'Unsplash / McDonald\'s'
  },
  {
    id: 'q-logo-4',
    packId: 'pack-famous-logos',
    order: 4,
    image: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'STARBUCKS',
    alternativeAcceptedAnswers: ['STARBUCKS COFFEE'],
    difficulty: 'Easy',
    hint: 'Global coffeehouse chain with a twin-tailed Siren logo.',
    triviaFact: 'Starbucks was named after the first mate Starbuck in Herman Melville’s classic novel Moby-Dick.',
    category: 'Logos & Brands',
    tags: ['coffee', 'brand']
  },
  {
    id: 'q-logo-5',
    packId: 'pack-famous-logos',
    order: 5,
    image: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TESLA',
    alternativeAcceptedAnswers: ['TESLA MOTORS'],
    difficulty: 'Medium',
    hint: 'Electric vehicle manufacturer led by Elon Musk.',
    triviaFact: 'The Tesla "T" logo isn’t just a T—it represents a cross-section of an electric motor rotor!',
    category: 'Logos & Brands',
    tags: ['car', 'tech', 'electric']
  },
  {
    id: 'q-logo-6',
    packId: 'pack-famous-logos',
    order: 6,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PEPSI',
    alternativeAcceptedAnswers: ['PEPSI COLA'],
    difficulty: 'Easy',
    hint: 'Famous red, white, and blue globe soft drink brand.',
    triviaFact: 'Pepsi was originally created in 1893 as "Brad’s Drink" before being renamed Pepsi-Cola in 1898.',
    category: 'Logos & Brands',
    tags: ['beverage', 'soda']
  },
  {
    id: 'q-logo-7',
    packId: 'pack-famous-logos',
    order: 7,
    image: 'https://images.unsplash.com/photo-1523474253046-8cd2748b5fd2?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'AMAZON',
    alternativeAcceptedAnswers: ['AMAZON COM'],
    difficulty: 'Easy',
    hint: 'E-commerce giant with an arrow pointing from A to Z.',
    triviaFact: 'The arrow in the Amazon logo points from A to Z, showing they sell everything, and forms a subtle smile!',
    category: 'Logos & Brands',
    tags: ['tech', 'shopping']
  },
  {
    id: 'q-logo-8',
    packId: 'pack-famous-logos',
    order: 8,
    image: 'https://images.unsplash.com/photo-1614680376593-902f749f705c?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SPOTIFY',
    alternativeAcceptedAnswers: ['SPOTIFY MUSIC'],
    difficulty: 'Easy',
    hint: 'Green music streaming service with sound wave lines.',
    triviaFact: 'Spotify was launched in Stockholm, Sweden in 2008 and is now the world’s largest audio streaming platform.',
    category: 'Logos & Brands',
    tags: ['music', 'streaming']
  },
  {
    id: 'q-logo-9',
    packId: 'pack-famous-logos',
    order: 9,
    image: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'LEGO',
    alternativeAcceptedAnswers: ['LEGO BRICKS'],
    difficulty: 'Medium',
    hint: 'Danish toy company famous for plastic interlocking bricks.',
    triviaFact: 'The word LEGO comes from the Danish words "Leg Godt", which translates to "Play Well".',
    category: 'Logos & Brands',
    tags: ['toys', 'brand']
  },
  {
    id: 'q-logo-10',
    packId: 'pack-famous-logos',
    order: 10,
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TARGET',
    alternativeAcceptedAnswers: ['TARGET STORES'],
    difficulty: 'Medium',
    hint: 'Retail giant with a red bullseye logo.',
    triviaFact: 'Target’s mascot is a white Bull Terrier named "Bullseye" with a red target painted over his left eye.',
    category: 'Logos & Brands',
    tags: ['retail', 'shopping']
  },

  // --- PACK: World Flags (10 Questions) ---
  {
    id: 'q-flag-1',
    packId: 'pack-world-flags',
    order: 1,
    image: 'https://images.unsplash.com/photo-1528164344705-47542687990d?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'JAPAN',
    alternativeAcceptedAnswers: ['NIPPON'],
    difficulty: 'Easy',
    hint: 'White background with a solid red circle in the center.',
    triviaFact: 'The red disc on Japan’s flag represents the sun goddess Amaterasu and the rising sun.',
    category: 'World Flags',
    tags: ['flag', 'asia']
  },
  {
    id: 'q-flag-2',
    packId: 'pack-world-flags',
    order: 2,
    image: 'https://images.unsplash.com/photo-1517935706615-2717063c2225?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'CANADA',
    alternativeAcceptedAnswers: ['CANADIAN FLAG'],
    difficulty: 'Easy',
    hint: 'Red and white flag featuring an 11-pointed red maple leaf.',
    triviaFact: 'Canada’s red maple leaf flag was officially adopted in 1965 after a national debate known as the Great Flag Debate.',
    category: 'World Flags',
    tags: ['flag', 'americas']
  },
  {
    id: 'q-flag-3',
    packId: 'pack-world-flags',
    order: 3,
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'BRAZIL',
    alternativeAcceptedAnswers: ['BRASIL'],
    difficulty: 'Medium',
    hint: 'Green flag with a yellow diamond and blue globe bearing 27 stars.',
    triviaFact: 'The motto on Brazil’s flag reads "Ordem e Progresso" (Order and Progress), inspired by Auguste Comte’s positivist motto.',
    category: 'World Flags',
    tags: ['flag', 'south-america']
  },
  {
    id: 'q-flag-4',
    packId: 'pack-world-flags',
    order: 4,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'UNITED KINGDOM',
    alternativeAcceptedAnswers: ['UK', 'GREAT BRITAIN', 'UNION JACK'],
    difficulty: 'Easy',
    hint: 'Famous Union Jack flag combining crosses of St George, St Andrew, and St Patrick.',
    triviaFact: 'Wales is not represented on the Union Jack flag because Wales was already united with England when the flag was designed in 1606.',
    category: 'World Flags',
    tags: ['flag', 'europe']
  },
  {
    id: 'q-flag-5',
    packId: 'pack-world-flags',
    order: 5,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'FRANCE',
    alternativeAcceptedAnswers: ['FRENCH REPUBLIC'],
    difficulty: 'Easy',
    hint: 'Blue, white, and red vertical tricolour flag.',
    triviaFact: 'The French Tricolour flag came into prominence during the French Revolution in 1789.',
    category: 'World Flags',
    tags: ['flag', 'europe']
  },
  {
    id: 'q-flag-6',
    packId: 'pack-world-flags',
    order: 6,
    image: 'https://images.unsplash.com/photo-1523482580672-f109ba8cb9be?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'AUSTRALIA',
    alternativeAcceptedAnswers: ['AUST'],
    difficulty: 'Medium',
    hint: 'Blue flag with Union Jack and the Southern Cross constellation.',
    triviaFact: 'The large 7-pointed star below the Union Jack represents the six original states plus Australia’s territories.',
    category: 'World Flags',
    tags: ['flag', 'oceania']
  },
  {
    id: 'q-flag-7',
    packId: 'pack-world-flags',
    order: 7,
    image: 'https://images.unsplash.com/photo-1576485290814-1c72aa4bbb8e?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SOUTH AFRICA',
    alternativeAcceptedAnswers: ['RSA'],
    difficulty: 'Hard',
    hint: 'Rainbow nation flag with a prominent Y-shaped horizontal band.',
    triviaFact: 'South Africa’s flag has six distinct colors, making it one of the most colorful national flags in the world.',
    category: 'World Flags',
    tags: ['flag', 'africa']
  },
  {
    id: 'q-flag-8',
    packId: 'pack-world-flags',
    order: 8,
    image: 'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'GERMANY',
    alternativeAcceptedAnswers: ['DEUTSCHLAND'],
    difficulty: 'Easy',
    hint: 'Horizontal tricolour of black, red, and gold.',
    triviaFact: 'Black, red, and gold were the colors of the uniforms worn by the Lützow Free Corps during the Napoleonic Wars.',
    category: 'World Flags',
    tags: ['flag', 'europe']
  },
  {
    id: 'q-flag-9',
    packId: 'pack-world-flags',
    order: 9,
    image: 'https://images.unsplash.com/photo-1529154036614-a60975f5c760?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'ITALY',
    alternativeAcceptedAnswers: ['ITALIA'],
    difficulty: 'Easy',
    hint: 'Green, white, and red vertical tricolour flag.',
    triviaFact: 'Green represents the country’s plains and hills, white represents the snow-capped Alps, and red represents blood spilled in wars.',
    category: 'World Flags',
    tags: ['flag', 'europe']
  },
  {
    id: 'q-flag-10',
    packId: 'pack-world-flags',
    order: 10,
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'JAMAICA',
    alternativeAcceptedAnswers: ['JAMAICAN FLAG'],
    difficulty: 'Hard',
    hint: 'Gold diagonal cross with green and black triangular fields.',
    triviaFact: 'Jamaica is the only current national flag that does not contain any red, white, or blue!',
    category: 'World Flags',
    tags: ['flag', 'caribbean']
  },

  // --- PACK: Movie Heroes & Legends (10 Questions) ---
  {
    id: 'q-movie-1',
    packId: 'pack-movie-icons',
    order: 1,
    image: 'https://images.unsplash.com/photo-1608889175123-8ee362201f81?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'DARTH VADER',
    alternativeAcceptedAnswers: ['VADER', 'ANAKIN SKYWALKER'],
    difficulty: 'Easy',
    hint: 'Dark Lord of the Sith with a black helmet and red lightsaber.',
    triviaFact: 'Darth Vader’s iconic breathing sound was created by sound designer Ben Burtt recording himself breathing through a scuba regulator.',
    category: 'Movies & TV',
    tags: ['starwars', 'villain', 'sci-fi']
  },
  {
    id: 'q-movie-2',
    packId: 'pack-movie-icons',
    order: 2,
    image: 'https://images.unsplash.com/photo-1618336753974-aae8e04506aa?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'HARRY POTTER',
    alternativeAcceptedAnswers: ['POTTER', 'BOY WHO LIVED'],
    difficulty: 'Easy',
    hint: 'Wizard boy with lightning bolt scar and round glasses.',
    triviaFact: 'Daniel Radcliffe went through 160 pairs of glasses and over 70 wands while filming the 8 Harry Potter movies!',
    category: 'Movies & TV',
    tags: ['wizard', 'magic', 'fantasy']
  },
  {
    id: 'q-movie-3',
    packId: 'pack-movie-icons',
    order: 3,
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'BATMAN',
    alternativeAcceptedAnswers: ['BRUCE WAYNE', 'DARK KNIGHT'],
    difficulty: 'Easy',
    hint: 'The Caped Crusader protecting Gotham City.',
    triviaFact: 'Batman made his first comic book debut in Detective Comics #27 in May 1939.',
    category: 'Movies & TV',
    tags: ['dc', 'superhero']
  },
  {
    id: 'q-movie-4',
    packId: 'pack-movie-icons',
    order: 4,
    image: 'https://images.unsplash.com/photo-1635863138275-d9b33299680b?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SPIDERMAN',
    alternativeAcceptedAnswers: ['SPIDER MAN', 'PETER PARKER'],
    difficulty: 'Easy',
    hint: 'Web-slinging superhero created by Stan Lee and Steve Ditko.',
    triviaFact: 'Spider-Man was initially rejected by Marvel publisher Martin Goodman because he believed people hated spiders!',
    category: 'Movies & TV',
    tags: ['marvel', 'superhero']
  },
  {
    id: 'q-movie-5',
    packId: 'pack-movie-icons',
    order: 5,
    image: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PIKACHU',
    alternativeAcceptedAnswers: ['POKEMON PIKACHU'],
    difficulty: 'Easy',
    hint: 'Yellow electric-type mouse Pokémon and mascot of the franchise.',
    triviaFact: 'Pikachu’s name comes from "pika" (the Japanese word for spark) and "chu" (the sound a mouse makes).',
    category: 'Movies & TV',
    tags: ['pokemon', 'anime']
  },
  {
    id: 'q-movie-6',
    packId: 'pack-movie-icons',
    order: 6,
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SHERLOCK',
    alternativeAcceptedAnswers: ['SHERLOCK HOLMES'],
    difficulty: 'Medium',
    hint: 'Famous Baker Street detective with deerstalker hat and pipe.',
    triviaFact: 'Sherlock Holmes holds the Guinness World Record as the most portrayed human literary character in film and TV history.',
    category: 'Movies & TV',
    tags: ['detective', 'classics']
  },
  {
    id: 'q-movie-7',
    packId: 'pack-movie-icons',
    order: 7,
    image: 'https://images.unsplash.com/photo-1594736797933-d0501ba2fe65?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'BUZZ LIGHTYEAR',
    alternativeAcceptedAnswers: ['BUZZ', 'LIGHTYEAR'],
    difficulty: 'Medium',
    hint: 'Space Ranger action figure from Toy Story: "To infinity and beyond!"',
    triviaFact: 'Buzz Lightyear was named in honor of Apollo 11 astronaut Edwin "Buzz" Aldrin.',
    category: 'Movies & TV',
    tags: ['pixar', 'disney', 'animation']
  },
  {
    id: 'q-movie-8',
    packId: 'pack-movie-icons',
    order: 8,
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'INDIANA JONES',
    alternativeAcceptedAnswers: ['INDY', 'HENRY JONES JR'],
    difficulty: 'Hard',
    hint: 'Archaeologist adventurer with a fedora, whip, and fear of snakes.',
    triviaFact: 'George Lucas named Indiana Jones after his beloved Alaskan Malamute dog named Indiana.',
    category: 'Movies & TV',
    tags: ['adventure', 'classics']
  },
  {
    id: 'q-movie-9',
    packId: 'pack-movie-icons',
    order: 9,
    image: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'YODA',
    alternativeAcceptedAnswers: ['MASTER YODA'],
    difficulty: 'Medium',
    hint: 'Grand Master of the Jedi Order: "Do or do not, there is no try."',
    triviaFact: 'Yoda’s face was partly modeled after Albert Einstein to give him a wise and intelligent expression.',
    category: 'Movies & TV',
    tags: ['starwars', 'jedi']
  },
  {
    id: 'q-movie-10',
    packId: 'pack-movie-icons',
    order: 10,
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'IRON MAN',
    alternativeAcceptedAnswers: ['TONY STARK', 'IRONMAN'],
    difficulty: 'Medium',
    hint: 'Genius billionaire playboy philanthropist inside powered armor.',
    triviaFact: 'Robert Downey Jr. stored food all over the Avengers movie set, including in the lab cabinets, which was unscripted!',
    category: 'Movies & TV',
    tags: ['marvel', 'avengers']
  },

  // --- PACK: Animals of the Wild (10 Questions) ---
  {
    id: 'q-animal-1',
    packId: 'pack-wild-animals',
    order: 1,
    image: 'https://images.unsplash.com/photo-1564349683136-77e08dba1ef9?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PANDA',
    alternativeAcceptedAnswers: ['GIANT PANDA', 'PANDA BEAR'],
    difficulty: 'Easy',
    hint: 'Black and white bamboo-eating bear native to China.',
    triviaFact: 'Giant Pandas spend up to 12 hours a day eating bamboo to satisfy their dietary needs.',
    category: 'Wild Animals',
    tags: ['animal', 'china', 'bear']
  },
  {
    id: 'q-animal-2',
    packId: 'pack-wild-animals',
    order: 2,
    image: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'FLAMINGO',
    alternativeAcceptedAnswers: ['GREATER FLAMINGO'],
    difficulty: 'Easy',
    hint: 'Bright pink wading bird that stands on one leg.',
    triviaFact: 'Flamingos get their pink color from carotenoid pigments in the algae and crustaceans they eat.',
    category: 'Wild Animals',
    tags: ['bird', 'pink', 'nature']
  },
  {
    id: 'q-animal-3',
    packId: 'pack-wild-animals',
    order: 3,
    image: 'https://images.unsplash.com/photo-1550358864-518f202c02ba?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'CHAMELEON',
    alternativeAcceptedAnswers: ['PANTHER CHAMELEON'],
    difficulty: 'Medium',
    hint: 'Reptile famous for color-changing skin and independently mobile eyes.',
    triviaFact: 'Chameleons change color primarily for social signaling and temperature regulation rather than camouflage.',
    category: 'Wild Animals',
    tags: ['reptile', 'exotic']
  },
  {
    id: 'q-animal-4',
    packId: 'pack-wild-animals',
    order: 4,
    image: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'CHEETAH',
    alternativeAcceptedAnswers: ['CHEETAH CAT'],
    difficulty: 'Easy',
    hint: 'Fastest land mammal on Earth with distinctive black tear tracks.',
    triviaFact: 'Cheetahs can accelerate from 0 to 60 mph in just 3 seconds, faster than many sports cars!',
    category: 'Wild Animals',
    tags: ['feline', 'speed', 'africa']
  },
  {
    id: 'q-animal-5',
    packId: 'pack-wild-animals',
    order: 5,
    image: 'https://images.unsplash.com/photo-1459263516528-5b32f17088b6?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'KOALA',
    alternativeAcceptedAnswers: ['KOALA BEAR'],
    difficulty: 'Easy',
    hint: 'Eucalyptus-loving Australian marsupial with fluffy ears.',
    triviaFact: 'Koalas have human-like fingerprints that are virtually indistinguishable from human prints under a microscope.',
    category: 'Wild Animals',
    tags: ['australia', 'marsupial']
  },
  {
    id: 'q-animal-6',
    packId: 'pack-wild-animals',
    order: 6,
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'LION',
    alternativeAcceptedAnswers: ['AFRICAN LION', 'KING OF JUNGLE'],
    difficulty: 'Easy',
    hint: 'King of the Jungle with a majestic mane.',
    triviaFact: 'A lion’s roar can be heard from up to 5 miles (8 kilometers) away.',
    category: 'Wild Animals',
    tags: ['lion', 'safari']
  },
  {
    id: 'q-animal-7',
    packId: 'pack-wild-animals',
    order: 7,
    image: 'https://images.unsplash.com/photo-1551085254-e96b210df58a?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TOUCAN',
    alternativeAcceptedAnswers: ['TOUCAN BIRD'],
    difficulty: 'Medium',
    hint: 'Tropical bird with an enormous colorful beak.',
    triviaFact: 'Despite its large size, a toucan’s bill is extremely lightweight because it is made of spongy keratin.',
    category: 'Wild Animals',
    tags: ['bird', 'rainforest']
  },
  {
    id: 'q-animal-8',
    packId: 'pack-wild-animals',
    order: 8,
    image: 'https://images.unsplash.com/photo-1574063413132-355dbfd83e0c?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'ORCA',
    alternativeAcceptedAnswers: ['KILLER WHALE', 'ORCA WHALE'],
    difficulty: 'Medium',
    hint: 'Black and white apex predator of the ocean (Killer Whale).',
    triviaFact: 'Orcas are actually the largest member of the dolphin family, not true whales!',
    category: 'Wild Animals',
    tags: ['ocean', 'whale']
  },
  {
    id: 'q-animal-9',
    packId: 'pack-wild-animals',
    order: 9,
    image: 'https://images.unsplash.com/photo-1534567153574-2b12153a87f0?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PEACOCK',
    alternativeAcceptedAnswers: ['PEAFOWL'],
    difficulty: 'Easy',
    hint: 'Male bird famous for iridescent blue green tail feathers.',
    triviaFact: 'Only males are called peacocks; females are called peahens, and their babies are called peachicks!',
    category: 'Wild Animals',
    tags: ['bird', 'feathers']
  },
  {
    id: 'q-animal-10',
    packId: 'pack-wild-animals',
    order: 10,
    image: 'https://images.unsplash.com/photo-1518791841217-8f162f1e1131?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'RED PANDA',
    alternativeAcceptedAnswers: ['LESSER PANDA'],
    difficulty: 'Hard',
    hint: 'Small reddish-brown mammal with a bushy ringed tail.',
    triviaFact: 'Red pandas were discovered 48 years before giant pandas and are not closely related to giant pandas!',
    category: 'Wild Animals',
    tags: ['panda', 'cute']
  },

  // --- PACK: Wonders & Landmarks (10 Questions) ---
  {
    id: 'q-landmark-1',
    packId: 'pack-world-landmarks',
    order: 1,
    image: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'EIFFEL TOWER',
    alternativeAcceptedAnswers: ['EIFFEL', 'PARIS TOWER'],
    difficulty: 'Easy',
    hint: 'Wrought-iron lattice tower on the Champ de Mars in Paris, France.',
    triviaFact: 'The Eiffel Tower grows up to 15 cm (6 inches) taller during summer due to thermal expansion of the iron!',
    category: 'Landmarks',
    tags: ['paris', 'france', 'tower']
  },
  {
    id: 'q-landmark-2',
    packId: 'pack-world-landmarks',
    order: 2,
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TAJ MAHAL',
    alternativeAcceptedAnswers: ['TAJMAHAL'],
    difficulty: 'Easy',
    hint: 'White marble mausoleum built in Agra, India by Emperor Shah Jahan.',
    triviaFact: 'The Taj Mahal changes color depending on the time of day, appearing pinkish in morning and golden at night.',
    category: 'Landmarks',
    tags: ['india', 'wonder']
  },
  {
    id: 'q-landmark-3',
    packId: 'pack-world-landmarks',
    order: 3,
    image: 'https://images.unsplash.com/photo-1605130284535-11dd9ede6523?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'STATUE OF LIBERTY',
    alternativeAcceptedAnswers: ['LIBERTY', 'LADY LIBERTY'],
    difficulty: 'Easy',
    hint: 'Colossal copper statue on Liberty Island in New York Harbor.',
    triviaFact: 'The Statue of Liberty was a gift from France to the United States in 1886 to celebrate the abolition of slavery and friendship.',
    category: 'Landmarks',
    tags: ['usa', 'newyork']
  },
  {
    id: 'q-landmark-4',
    packId: 'pack-world-landmarks',
    order: 4,
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'GREAT WALL OF CHINA',
    alternativeAcceptedAnswers: ['GREAT WALL', 'CHINA WALL'],
    difficulty: 'Medium',
    hint: 'Ancient fortification winding across the northern borders of China.',
    triviaFact: 'The Great Wall of China is over 21,000 kilometers long and took over 2,000 years to construct!',
    category: 'Landmarks',
    tags: ['china', 'history']
  },
  {
    id: 'q-landmark-5',
    packId: 'pack-world-landmarks',
    order: 5,
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'COLOSSEUM',
    alternativeAcceptedAnswers: ['ROMAN COLOSSEUM', 'FLAVIAN AMPHITHEATRE'],
    difficulty: 'Medium',
    hint: 'Ancient oval amphitheatre in the center of Rome, Italy.',
    triviaFact: 'The Roman Colosseum could hold an estimated 50,000 to 80,000 spectators for gladiatorial contests.',
    category: 'Landmarks',
    tags: ['rome', 'italy']
  },
  {
    id: 'q-landmark-6',
    packId: 'pack-world-landmarks',
    order: 6,
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'MACHU PICCHU',
    alternativeAcceptedAnswers: ['MACHUPICCHU'],
    difficulty: 'Hard',
    hint: '15th-century Inca citadel located in the Andes Mountains of Peru.',
    triviaFact: 'Machu Picchu was built without mortar; the stones were cut so precisely that not even a knife blade can fit between them.',
    category: 'Landmarks',
    tags: ['peru', 'incan']
  },
  {
    id: 'q-landmark-7',
    packId: 'pack-world-landmarks',
    order: 7,
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PYRAMIDS OF GIZA',
    alternativeAcceptedAnswers: ['GIZA PYRAMIDS', 'GREAT PYRAMID'],
    difficulty: 'Easy',
    hint: 'Ancient monumental tombs near Cairo, Egypt guarding the Sphinx.',
    triviaFact: 'The Great Pyramid of Giza is the oldest of the Seven Wonders of the Ancient World and the only one still largely intact.',
    category: 'Landmarks',
    tags: ['egypt', 'ancient']
  },
  {
    id: 'q-landmark-8',
    packId: 'pack-world-landmarks',
    order: 8,
    image: 'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SYDNEY OPERA HOUSE',
    alternativeAcceptedAnswers: ['SYDNEY OPERA'],
    difficulty: 'Medium',
    hint: 'Multi-venue performing arts centre in Sydney Harbour with sail-like roofs.',
    triviaFact: 'The roof tiles of the Sydney Opera House were imported from Sweden and self-clean when rained upon!',
    category: 'Landmarks',
    tags: ['australia', 'sydney']
  },
  {
    id: 'q-landmark-9',
    packId: 'pack-world-landmarks',
    order: 9,
    image: 'https://images.unsplash.com/photo-1529655683826-aba9b3e77383?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'BIG BEN',
    alternativeAcceptedAnswers: ['ELIZABETH TOWER', 'CLOCK TOWER'],
    difficulty: 'Easy',
    hint: 'Iconic clock tower at the north end of the Houses of Parliament in London.',
    triviaFact: 'Big Ben is actually the nickname for the Great Bell inside the clock tower, not the tower itself (which is named Elizabeth Tower).',
    category: 'Landmarks',
    tags: ['london', 'uk']
  },
  {
    id: 'q-landmark-10',
    packId: 'pack-world-landmarks',
    order: 10,
    image: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'MOUNT FUJI',
    alternativeAcceptedAnswers: ['FUJISAN', 'MT FUJI'],
    difficulty: 'Medium',
    hint: 'Active stratovolcano and highest peak in Japan.',
    triviaFact: 'Mount Fuji is an active volcano that last erupted in 1707 and is considered a sacred mountain in Shinto tradition.',
    category: 'Landmarks',
    tags: ['japan', 'mountain']
  },

  // --- PACK: Retro Video Game Classics (8 Questions) ---
  {
    id: 'q-game-1',
    packId: 'pack-retro-games',
    order: 1,
    image: 'https://images.unsplash.com/photo-1579373903781-fd5c0c30c4cd?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PACMAN',
    alternativeAcceptedAnswers: ['PAC MAN', 'PUCK MAN'],
    difficulty: 'Easy',
    hint: 'Yellow pie-shaped character munching dots and fleeing ghosts.',
    triviaFact: 'Pac-Man was originally named "Puck Man" in Japan, but was renamed for North America to prevent vandalizing the name!',
    category: 'Retro Video Games',
    tags: ['arcade', 'namco']
  },
  {
    id: 'q-game-2',
    packId: 'pack-retro-games',
    order: 2,
    image: 'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SUPER MARIO',
    alternativeAcceptedAnswers: ['MARIO', 'MARIO BROS'],
    difficulty: 'Easy',
    hint: 'Mustachioed plumber jumping on Goombas to save Princess Peach.',
    triviaFact: 'Mario was originally named "Jumpman" in the 1981 Donkey Kong arcade game before being renamed Mario after Nintendo’s warehouse landlord.',
    category: 'Retro Video Games',
    tags: ['nintendo', 'platformer']
  },
  {
    id: 'q-game-3',
    packId: 'pack-retro-games',
    order: 3,
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SONIC THE HEDGEHOG',
    alternativeAcceptedAnswers: ['SONIC', 'SONIC HEDGEHOG'],
    difficulty: 'Easy',
    hint: 'Blue hedgehog running at supersonic speeds collecting gold rings.',
    triviaFact: 'Sonic’s signature blue color was chosen to match SEGA’s corporate logo!',
    category: 'Retro Video Games',
    tags: ['sega', 'speed']
  },
  {
    id: 'q-game-4',
    packId: 'pack-retro-games',
    order: 4,
    image: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TETRIS',
    alternativeAcceptedAnswers: ['TETRIS BLOCKS'],
    difficulty: 'Easy',
    hint: 'Soviet tile-matching puzzle game with falling tetrominoes.',
    triviaFact: 'Tetris was invented in 1984 by Alexey Pajitnov at the USSR Academy of Sciences and is the best-selling puzzle game of all time.',
    category: 'Retro Video Games',
    tags: ['puzzle', 'arcade']
  },
  {
    id: 'q-game-5',
    packId: 'pack-retro-games',
    order: 5,
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'ZELDA',
    alternativeAcceptedAnswers: ['LINK', 'LEGEND OF ZELDA'],
    difficulty: 'Medium',
    hint: 'Action-adventure series starring Link wielding the Master Sword.',
    triviaFact: 'Princess Zelda was named after Zelda Fitzgerald, the novelist wife of author F. Scott Fitzgerald.',
    category: 'Retro Video Games',
    tags: ['nintendo', 'adventure']
  },
  {
    id: 'q-game-6',
    packId: 'pack-retro-games',
    order: 6,
    image: 'https://images.unsplash.com/photo-1551103782-8ab07afd45c1?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SPACE INVADERS',
    alternativeAcceptedAnswers: ['SPACEINVADERS'],
    difficulty: 'Hard',
    hint: 'Classic 1978 arcade shoot-em-up featuring descending alien fleets.',
    triviaFact: 'Space Invaders was so popular upon release in Japan that it caused a nationwide shortage of 100-yen coins!',
    category: 'Retro Video Games',
    tags: ['arcade', 'retro']
  },
  {
    id: 'q-game-7',
    packId: 'pack-retro-games',
    order: 7,
    image: 'https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'MINECRAFT',
    alternativeAcceptedAnswers: ['MINECRAFT GAME'],
    difficulty: 'Easy',
    hint: 'Blocky sandbox survival game where players mine and build.',
    triviaFact: 'Minecraft is the best-selling video game in history with over 300 million copies sold worldwide.',
    category: 'Retro Video Games',
    tags: ['sandbox', 'building']
  },
  {
    id: 'q-game-8',
    packId: 'pack-retro-games',
    order: 8,
    image: 'https://images.unsplash.com/photo-1613771404784-3a5686aa2be3?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'POKEMON',
    alternativeAcceptedAnswers: ['POKEMON RED', 'POCKET MONSTERS'],
    difficulty: 'Easy',
    hint: 'Catch, train, and battle pocket monsters to become a Master.',
    triviaFact: 'Pokémon was created by Satoshi Tajiri, inspired by his childhood hobby of collecting insects.',
    category: 'Retro Video Games',
    tags: ['nintendo', 'rpg']
  },

  // --- PACK: Food & Delights (8 Questions) ---
  {
    id: 'q-food-1',
    packId: 'pack-food-delights',
    order: 1,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'PIZZA',
    alternativeAcceptedAnswers: ['PEPPERONI PIZZA', 'ITALIAN PIZZA'],
    difficulty: 'Easy',
    hint: 'Flat oven-baked bread topped with tomato sauce and melted cheese.',
    triviaFact: 'The world’s first pizzeria, Antica Pizzeria Port’Alba, opened in Naples, Italy in 1830 and is still open today!',
    category: 'Food & Delights',
    tags: ['pizza', 'italian']
  },
  {
    id: 'q-food-2',
    packId: 'pack-food-delights',
    order: 2,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'SUSHI',
    alternativeAcceptedAnswers: ['SUSHI ROLL', 'NIGIRI'],
    difficulty: 'Easy',
    hint: 'Traditional Japanese dish of seasoned rice paired with fresh raw fish.',
    triviaFact: 'Nori (seaweed) used in sushi rolls was originally scraped off wooden harbor pilings and dried into sheets!',
    category: 'Food & Delights',
    tags: ['japan', 'seafood']
  },
  {
    id: 'q-food-3',
    packId: 'pack-food-delights',
    order: 3,
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TACO',
    alternativeAcceptedAnswers: ['MEXICAN TACO'],
    difficulty: 'Easy',
    hint: 'Traditional Mexican dish with a folded tortilla filled with meat and salsa.',
    triviaFact: 'The word "taco" originally referred to gunpowder charges used by 18th-century Mexican silver miners.',
    category: 'Food & Delights',
    tags: ['mexican', 'tortilla']
  },
  {
    id: 'q-food-4',
    packId: 'pack-food-delights',
    order: 4,
    image: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'DONUT',
    alternativeAcceptedAnswers: ['DOUGHNUT'],
    difficulty: 'Easy',
    hint: 'Fried ring-shaped sweet dough glazed or sprinkled with toppings.',
    triviaFact: 'In 1920, Russian immigrant Adolph Levitt invented the automated doughnut machine in New York City.',
    category: 'Food & Delights',
    tags: ['dessert', 'sweet']
  },
  {
    id: 'q-food-5',
    packId: 'pack-food-delights',
    order: 5,
    image: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'CROISSANT',
    alternativeAcceptedAnswers: ['FRENCH CROISSANT'],
    difficulty: 'Medium',
    hint: 'Flaky crescent-shaped buttery pastry originating in Austria and perfected in France.',
    triviaFact: 'Croissants actually originated in Vienna, Austria, where they were known as "Kipferl" before moving to France in 1839.',
    category: 'Food & Delights',
    tags: ['pastry', 'bakery']
  },
  {
    id: 'q-food-6',
    packId: 'pack-food-delights',
    order: 6,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'HAMBURGER',
    alternativeAcceptedAnswers: ['BURGER', 'CHEESEBURGER'],
    difficulty: 'Easy',
    hint: 'Round ground beef patty served inside a sliced bun.',
    triviaFact: 'Americans consume an estimated 50 billion burgers every year, which equals roughly 3 burgers per week per person!',
    category: 'Food & Delights',
    tags: ['american', 'fastfood']
  },
  {
    id: 'q-food-7',
    packId: 'pack-food-delights',
    order: 7,
    image: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'RAMEN',
    alternativeAcceptedAnswers: ['RAMEN NOODLES'],
    difficulty: 'Medium',
    hint: 'Japanese noodle soup served in rich broth with chashu pork.',
    triviaFact: 'Instant ramen was invented by Momofuku Ando in Japan in 1958 and was voted Japan’s greatest 20th-century invention.',
    category: 'Food & Delights',
    tags: ['japan', 'soup']
  },
  {
    id: 'q-food-8',
    packId: 'pack-food-delights',
    order: 8,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'AVOCADO',
    alternativeAcceptedAnswers: ['AVOCADO FRUIT'],
    difficulty: 'Easy',
    hint: 'Creamy green superfood berry with a large pit inside.',
    triviaFact: 'Botanically, avocados are single-seeded berries, and they are nicknamed "alligator pears" due to their dark green bumpy skin.',
    category: 'Food & Delights',
    tags: ['fruit', 'healthy']
  },

  // --- PACK: Pop Stars & Rock Legends (8 Questions) ---
  {
    id: 'q-music-1',
    packId: 'pack-music-icons',
    order: 1,
    image: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'MICHAEL JACKSON',
    alternativeAcceptedAnswers: ['MJ', 'KING OF POP'],
    difficulty: 'Easy',
    hint: 'The King of Pop famous for the Moonwalk, Thriller, and Billie Jean.',
    triviaFact: 'Michael Jackson’s Thriller album released in 1982 remains the best-selling music album of all time with over 70 million copies sold.',
    category: 'Pop Stars & Music',
    tags: ['pop', 'legend']
  },
  {
    id: 'q-music-2',
    packId: 'pack-music-icons',
    order: 2,
    image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'THE BEATLES',
    alternativeAcceptedAnswers: ['BEATLES', 'FAB FOUR'],
    difficulty: 'Easy',
    hint: 'Liverpool band consisting of John, Paul, George, and Ringo.',
    triviaFact: 'The Beatles hold the record for the most number-one hits on the Billboard Hot 100 chart with 20 total chart-toppers.',
    category: 'Pop Stars & Music',
    tags: ['rock', '60s']
  },
  {
    id: 'q-music-3',
    packId: 'pack-music-icons',
    order: 3,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'TAYLOR SWIFT',
    alternativeAcceptedAnswers: ['SWIFT', 'TAY SWIFT'],
    difficulty: 'Easy',
    hint: 'Grammy-winning pop superstar famous for The Eras Tour.',
    triviaFact: 'Taylor Swift became the first artist in history to win Album of the Year at the Grammys four times!',
    category: 'Pop Stars & Music',
    tags: ['pop', 'eras']
  },
  {
    id: 'q-music-4',
    packId: 'pack-music-icons',
    order: 4,
    image: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'ELVIS PRESLEY',
    alternativeAcceptedAnswers: ['ELVIS', 'KING OF ROCK'],
    difficulty: 'Easy',
    hint: 'The King of Rock and Roll famous for Hound Dog and Jailhouse Rock.',
    triviaFact: 'Elvis Presley purchased his famous Graceland mansion in Memphis, Tennessee in 1957 for just $102,500.',
    category: 'Pop Stars & Music',
    tags: ['rock', '50s']
  },
  {
    id: 'q-music-5',
    packId: 'pack-music-icons',
    order: 5,
    image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'QUEEN',
    alternativeAcceptedAnswers: ['FREDDIE MERCURY'],
    difficulty: 'Medium',
    hint: 'British rock band led by Freddie Mercury: "Bohemian Rhapsody".',
    triviaFact: 'Freddie Mercury had a 4-octave vocal range and designed the Queen crest logo himself using his art college degree!',
    category: 'Pop Stars & Music',
    tags: ['rock', 'queen']
  },
  {
    id: 'q-music-6',
    packId: 'pack-music-icons',
    order: 6,
    image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'BEYONCE',
    alternativeAcceptedAnswers: ['BEYONCE KNOWLES', 'QUEEN BAY'],
    difficulty: 'Medium',
    hint: 'Pop icon known as Queen Bey and former lead singer of Destiny’s Child.',
    triviaFact: 'Beyoncé holds the record for the most Grammy Award wins in history by any individual artist (32 Grammys)!',
    category: 'Pop Stars & Music',
    tags: ['pop', 'rnb']
  },
  {
    id: 'q-music-7',
    packId: 'pack-music-icons',
    order: 7,
    image: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'ELTON JOHN',
    alternativeAcceptedAnswers: ['SIR ELTON JOHN', 'ROCKETMAN'],
    difficulty: 'Medium',
    hint: 'Legendary flamboyant British pianist famous for Rocket Man and Tiny Dancer.',
    triviaFact: 'Elton John’s 1997 single "Candle in the Wind 1997" is the second best-selling physical single of all time!',
    category: 'Pop Stars & Music',
    tags: ['piano', 'pop']
  },
  {
    id: 'q-music-8',
    packId: 'pack-music-icons',
    order: 8,
    image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=800&q=80',
    correctAnswer: 'DAVID BOWIE',
    alternativeAcceptedAnswers: ['BOWIE', 'ZIGGY STARDUST'],
    difficulty: 'Hard',
    hint: 'Musical chameleon behind Ziggy Stardust, Space Oddity, and Heroes.',
    triviaFact: 'David Bowie’s distinctive eyes were caused by a condition called anisocoria resulting from a schoolyard fight over a girl!',
    category: 'Pop Stars & Music',
    tags: ['rock', 'glam']
  }
];

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'ach-first-correct',
    title: 'First Step',
    description: 'Answer your very first picture question correctly.',
    icon: 'CheckCircle2',
    category: 'gameplay',
    targetValue: 1,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 25,
    rewardXP: 50,
  },
  {
    id: 'ach-10-correct',
    title: 'Trivia Enthusiast',
    description: 'Answer 10 picture questions correctly.',
    icon: 'Zap',
    category: 'gameplay',
    targetValue: 10,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 50,
    rewardXP: 100,
  },
  {
    id: 'ach-50-correct',
    title: 'Picture Sleuth',
    description: 'Answer 50 picture questions correctly.',
    icon: 'Eye',
    category: 'gameplay',
    targetValue: 50,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 150,
    rewardXP: 300,
  },
  {
    id: 'ach-first-pack',
    title: 'Pack Pioneer',
    description: '100% complete your first quiz pack.',
    icon: 'PackageCheck',
    category: 'packs',
    targetValue: 1,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 100,
    rewardXP: 200,
  },
  {
    id: 'ach-streak-3',
    title: 'On Fire',
    description: 'Achieve a 3-day daily streak.',
    icon: 'Flame',
    category: 'streaks',
    targetValue: 3,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 75,
    rewardXP: 150,
  },
  {
    id: 'ach-no-hint-pack',
    title: 'Master Mind',
    description: 'Complete an entire pack without using a single hint!',
    icon: 'Brain',
    category: 'hints',
    targetValue: 1,
    currentValue: 0,
    isUnlocked: false,
    rewardCoins: 200,
    rewardXP: 400,
  }
];
